// <auto-generated />
using System;
using JustinaSimulator.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JustinaSimulator.API.Migrations
{
    [DbContext(typeof(JustinaDbContext))]
    [Migration("20260306023147_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("JustinaSimulator.Domain.Entities.Robot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DangersCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedClicks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalDistance")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trajectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WarningsCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Robots");
                });

            modelBuilder.Entity("JustinaSimulator.Domain.Entities.Robot", b =>
                {
                    b.OwnsOne("JustinaSimulator.Domain.Entities.Coordinate", "CurrentTarget", b1 =>
                        {
                            b1.Property<Guid>("RobotId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("X")
                                .HasColumnType("REAL")
                                .HasColumnName("CurrentX");

                            b1.Property<double>("Y")
                                .HasColumnType("REAL")
                                .HasColumnName("CurrentY");

                            b1.Property<double>("Z")
                                .HasColumnType("REAL")
                                .HasColumnName("CurrentZ");

                            b1.HasKey("RobotId");

                            b1.ToTable("Robots");

                            b1.WithOwner()
                                .HasForeignKey("RobotId");
                        });

                    b.Navigation("CurrentTarget")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
